name: Test loom (Mojang Pattern)
on: [push]

jobs:
  loom-action-mojang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 🔃
        uses: actions/checkout@v3

      - name: Installing Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies 🔨
        run: npm install

      - name: 🧪 Loom Action test
        uses: ./
        with:
          pattern: 'mojang'
          behavior_pack_path: 'addon/behavior_pack'
          resource_pack_path: 'addon/resource_pack'
